AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Metrics/AbcSize:
  Max: 19

Metrics/BlockLength:
  Exclude:
    - 'passenger_datadog.gemspec'
    - 'spec/**/*'

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - 'bin/passenger-datadog'

Style/Documentation:
  Enabled: false
