# frozen_string_literal: true

require 'rbconfig'

# Generates and installs the systemd unit for the collector.
#
# The unit is generated rather than shipped because the correct paths are only
# knowable on the target host: under rvm/rbenv/asdf the executable does not live
# in /usr/local/bin, and systemd's minimal PATH does not include the gem bin
# directory that `passenger-status` is installed into.
class ServiceInstaller
  class Error < StandardError; end

  UNIT_NAME = 'passenger-datadog.service'
  UNIT_DIR = '/etc/systemd/system'
  ENVIRONMENT_FILE = '/etc/default/passenger-datadog'

  # systemd starts services with a minimal PATH; these are its usual defaults,
  # which we extend with the directories the resolved binaries actually live in.
  BASE_PATH = %w[/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin].freeze

  UNIT_TEMPLATE = <<~UNIT
    # Generated by `passenger-datadog install-service` on this host.
    # Paths are resolved for this machine's Ruby; regenerate after a Ruby upgrade.
    [Unit]
    Description=Send Passenger stats to Datadog
    After=network-online.target
    Wants=network-online.target

    [Service]
    Type=notify
    NotifyAccess=main
    ExecStart=%<exec_start>s
    Environment=PATH=%<path>s
    # systemd inherits no gem environment, so pin the one this Ruby is using.
    Environment=GEM_HOME=%<gem_home>s
    Environment=GEM_PATH=%<gem_path>s
    # Optional: set DD_AGENT_HOST, DD_DOGSTATSD_PORT, DD_TAGS, etc.
    EnvironmentFile=-%<environment_file>s
    Restart=on-failure
    RestartSec=5s
    # Passenger recommends running passenger-status as root so it can see every
    # Passenger instance on the host.
    User=%<user>s
    Group=%<group>s

    [Install]
    WantedBy=multi-user.target
  UNIT

  attr_reader :user, :group, :unit_dir

  def initialize(user: 'root', group: 'root', unit_dir: UNIT_DIR, executable: nil,
                 passenger_status: nil, search_paths: nil, env: ENV)
    @user = user
    @group = group
    @unit_dir = unit_dir
    @executable = executable
    @passenger_status = passenger_status
    @search_paths = search_paths
    @env = env
  end

  def unit_path
    File.join(unit_dir, UNIT_NAME)
  end

  # Invoke Ruby explicitly so the unit does not depend on the shebang line or on
  # systemd's PATH resolving the executable.
  def exec_start
    "#{RbConfig.ruby} #{executable}"
  end

  def executable
    @executable ||= File.expand_path($PROGRAM_NAME)
  end

  # Everything systemd would normally have, plus the directories holding the
  # resolved Ruby and passenger-status, so the backtick call in the collector
  # can find passenger-status.
  def service_path
    ([File.dirname(passenger_status), File.dirname(RbConfig.ruby)] + BASE_PATH).uniq.join(':')
  end

  def passenger_status
    @passenger_status ||= which('passenger-status') ||
                          raise(Error, 'passenger-status not found; is the passenger gem installed for this ruby?')
  end

  # `passenger` is a runtime dependency, so passenger-status is installed
  # alongside this executable. Looking there first means the command still works
  # under `sudo`, whose secure_path strips rvm/rbenv directories from PATH.
  def search_paths
    @search_paths ||= [File.dirname(executable), Gem.bindir] + @env.fetch('PATH', '').split(File::PATH_SEPARATOR)
  end

  # Where this Ruby installs and looks up gems. Under rvm/rbenv these are set by
  # shell integration that systemd never runs, so they have to be baked in.
  def gem_home
    Gem.dir
  end

  def gem_path
    Gem.path.uniq.join(File::PATH_SEPARATOR)
  end

  def unit
    format(UNIT_TEMPLATE, exec_start: exec_start, path: service_path, gem_home: gem_home,
                          gem_path: gem_path, environment_file: ENVIRONMENT_FILE, user: user, group: group)
  end

  # Writes the unit and reloads systemd. Returns the path written.
  def install(force: false)
    require_root
    raise Error, "#{unit_path} already exists; pass --force to overwrite" if File.exist?(unit_path) && !force

    File.write(unit_path, unit)
    File.chmod(0o644, unit_path)
    daemon_reload
    unit_path
  end

  def uninstall
    require_root
    return nil unless File.exist?(unit_path)

    system('systemctl', 'disable', '--now', UNIT_NAME, out: File::NULL, err: File::NULL)
    File.delete(unit_path)
    daemon_reload
    unit_path
  end

  private

  def daemon_reload
    return if system('systemctl', 'daemon-reload')

    raise Error, 'systemctl daemon-reload failed'
  end

  def require_root
    return if Process.uid.zero?

    raise Error, 'must run as root to manage units in /etc/systemd/system (try sudo)'
  end

  def which(command)
    search_paths.each do |dir|
      candidate = File.join(dir, command)
      return candidate if File.executable?(candidate) && !File.directory?(candidate)
    end
    nil
  end
end
